import type { Meta, StoryObj } from '@storybook/react';
import React from 'react';
import { Box, Typography, Card, CardContent, Stack, Chip } from '@mui/material';
import * as tokens from '@luispmoraisc/ds-tokens';

const ColorToken = ({ name, value }: { name: string; value: string }) => {
  return (
    <Card sx={{ mb: 2, minWidth: 300 }}>
      <CardContent>
        <Stack direction="row" spacing={2} alignItems="center">
          <Box
            sx={{
              width: 40,
              height: 40,
              backgroundColor: value,
              borderRadius: 1,
              border: '1px solid #e0e0e0',
              flexShrink: 0,
            }}
          />
          <Box sx={{ flexGrow: 1 }}>
            <Typography
              variant="h6"
              sx={{ fontSize: '0.9rem', fontWeight: 600 }}
            >
              {name}
            </Typography>
            <Typography variant="body2" color="text.secondary">
              {value}
            </Typography>
            <Chip
              label={value}
              size="small"
              sx={{ mt: 1, fontFamily: 'monospace' }}
            />
          </Box>
        </Stack>
      </CardContent>
    </Card>
  );
};

const DesignTokensShowcase = () => {
  const colorTokens = Object.entries(tokens).filter(([key]) =>
    key.startsWith('COLOR_')
  );

  return (
    <Box sx={{ p: 3 }}>
      <Typography variant="h4" gutterBottom>
        Design Tokens
      </Typography>
      <Typography variant="body1" sx={{ mb: 4 }}>
        Design tokens automatically generated by Style Dictionary
      </Typography>
      <Box
        sx={{
          display: 'grid',
          gridTemplateColumns: 'repeat(auto-fit, minmax(300px, 1fr))',
          gap: 2,
          mb: 6,
        }}
      >
        {colorTokens.map(([name, value]) => (
          <ColorToken
            key={name}
            name={name.replace('COLOR_', '').replace(/_/g, ' ')}
            value={value as string}
          />
        ))}
      </Box>

      <Box sx={{ mt: 6 }}>
        <Typography variant="h6" sx={{ mt: 4, mb: 2 }}>
          How to use:
        </Typography>
        <Card sx={{ p: 3 }}>
          <Typography
            component="pre"
            sx={{ fontFamily: 'monospace', fontSize: '0.8rem' }}
          >
            {`import { COLOR_PRIMARY } from '@luispmoraisc/ds-tokens';

const theme = createTheme({
  palette: {
    primary: {
      main: COLOR_PRIMARY,
    },
  },
});`}
          </Typography>
        </Card>

        <Typography variant="h6" sx={{ mt: 4, mb: 2 }}>
          In a MUI component:
        </Typography>
        <Card sx={{ p: 3 }}>
          <Typography
            component="pre"
            sx={{ fontFamily: 'monospace', fontSize: '0.8rem' }}
          >
            {`import { COLOR_PRIMARY } from '@luispmoraisc/ds-tokens';

<Button sx={{ backgroundColor: COLOR_PRIMARY }}>
  Botão com cor primária
</Button>
`}
          </Typography>
        </Card>
      </Box>
    </Box>
  );
};

const meta = {
  title: 'Design System',
  component: DesignTokensShowcase,
} satisfies Meta<typeof DesignTokensShowcase>;

export default meta;

type Story = StoryObj<typeof DesignTokensShowcase>;

export const Colors: Story = {
  args: {},
};
