name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - development

permissions:
  actions: read
  contents: write
  packages: write

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref || github.ref_name }}
          fetch-depth: 0
          persist-credentials: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://npm.pkg.github.com'
          scope: '@luispmoraisc'
          always-auth: true
          cache: 'yarn'

      - name: Configure .npmrc
        run: |
          echo "@luispmoraisc:registry=https://npm.pkg.github.com/" > ~/.npmrc
          echo "//npm.pkg.github.com/:_authToken=${NODE_AUTH_TOKEN}" >> ~/.npmrc
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: yarn install

      - name: Run lint, test, build and typecheck
        run: npx nx run-many -t lint test build typecheck

      - name: Configure GitHub
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Release (development)
        if: github.ref_name == 'development' && github.event_name == 'pull_request'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx nx release --yes --preid=next

      - name: Release (default)
        if: github.ref_name == 'main' && github.event_name == 'push'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx nx release --yes

      - name: Push commit changes and tags
        run: git push origin --follow-tags HEAD:${{ github.head_ref || github.ref_name }}
